import {
  NAV_ITEM_TYPE_ITEM,
  NAV_ITEM_TYPE_COLLAPSE,
} from "@/constants/navigation.constant";
import type { NavigationTree } from "@/@types/navigation";

const navigationConfig: NavigationTree[] = [
  {
    key: "dashboard",
    path: "/dashobard",
    title: "Dashboard",
    translateKey: "dashboard",
    icon: "dashboard",
    type: NAV_ITEM_TYPE_ITEM,
    authority: [],
    subMenu: [],
  },
  // {
  //   key: "store",
  //   path: "/store",
  //   title: "Store",
  //   translateKey: "store",
  //   icon: "items",
  //   type: NAV_ITEM_TYPE_ITEM,
  //   authority: [],
  //   subMenu: [],
  // },
  // {
  //   key: "user",
  //   path: "/user",
  //   title: "User Management",
  //   translateKey: "user",
  //   icon: "user",
  //   type: NAV_ITEM_TYPE_ITEM,
  //   authority: [],
  //   subMenu: [],
  // },
  // {
  //   key: "club",
  //   path: "/club",
  //   title: "Club Management",
  //   translateKey: "club",
  //   icon: "user",
  //   type: NAV_ITEM_TYPE_ITEM,
  //   authority: [],
  //   subMenu: [],
  // },
  {
    key: "game",
    path: "/game",
    title: "By Customers",
    translateKey: "game",
    icon: "user",
    type: NAV_ITEM_TYPE_ITEM,
    authority: [],
    subMenu: [],
  },

  // {
  //   key: "leaderBoard",
  //   path: "/leaderboard",
  //   title: "LeaderBoard",
  //   translateKey: "leaderboard",
  //   icon: "leaderboard",
  //   type: NAV_ITEM_TYPE_ITEM,
  //   authority: [],
  //   subMenu: [],
  // },
  {
    key: "tournament",
    path: "/tournament",
    title: "By Company",
    translateKey: "tournament",
    icon: "payemnt",
    type: NAV_ITEM_TYPE_ITEM,
    authority: [],
    subMenu: [],
  },
  {
    key: "tournament",
    path: "/tournament",
    title: "For Specific User",
    translateKey: "tournament",
    icon: "payemnt",
    type: NAV_ITEM_TYPE_ITEM,
    authority: [],
    subMenu: [],
  },
  // {
  //   key: "payment",
  //   path: "/payment",
  //   title: "Transaction",
  //   translateKey: "payment",
  //   icon: "payemnt",
  //   type: NAV_ITEM_TYPE_ITEM,
  //   authority: [],
  //   subMenu: [],
  // },
  //   {
  //     key: "tournament",
  //     path: "/tournament",
  //     title: "Tournament Management",
  //     translateKey: "report",
  //     icon: "report",
  //     type: NAV_ITEM_TYPE_ITEM,
  //     authority: [],
  //     subMenu: [],
  //   },
  // {
  //   key: "PushNotification",
  //   path: "/PushNotification",
  //   title: "News/Alerts",
  //   translateKey: "News/Alerts",
  //   icon: "notification",
  //   type: NAV_ITEM_TYPE_ITEM,
  //   authority: [],
  //   subMenu: [],
  // },
  // {
  //   key: "spinMachine",
  //   path: "/SpinMachineConfiguration",
  //   title: "SpinMachineConfiguration",
  //   translateKey: "SpinMachineConfiguration",
  //   icon: "settings",
  //   type: NAV_ITEM_TYPE_ITEM,
  //   authority: [],
  //   subMenu: [],
  // },
];

export default navigationConfig;
