import {
  NAV_ITEM_TYPE_ITEM,
  NAV_ITEM_TYPE_COLLAPSE,
} from "@/constants/navigation.constant";
import type { NavigationTree } from "@/@types/navigation";

const navigationConfig: NavigationTree[] = [
  // {
  //   key: "store",
  //   path: "/store",
  //   title: "Store",
  //   translateKey: "store",
  //   icon: "items",
  //   type: NAV_ITEM_TYPE_ITEM,
  //   authority: [],
  //   subMenu: [],
  // },
  // {
  //   key: "user",
  //   path: "/user",
  //   title: "User Management",
  //   translateKey: "user",
  //   icon: "user",
  //   type: NAV_ITEM_TYPE_ITEM,
  //   authority: [],
  //   subMenu: [],
  // },
  // {
  //   key: "club",
  //   path: "/club",
  //   title: "Club Management",
  //   translateKey: "club",
  //   icon: "user",
  //   type: NAV_ITEM_TYPE_ITEM,
  //   authority: [],
  //   subMenu: [],
  // },
  {
    key: "inventrylist",
    path: "/inventrylist",
    title: "Company Sales",
    translateKey: "gaminventryliste",
    icon: "user",
    type: NAV_ITEM_TYPE_ITEM,
    authority: [],
    subMenu: [],
  },
  {
    key: "vendor-purchase",
    path: "/vendor-purchase",
    title: "Vendor Purchase",
    translateKey: "vendorPurchase",
    icon: "payemnt",
    type: NAV_ITEM_TYPE_ITEM,
    authority: [],
    subMenu: [],
  },

  // {
  //   key: "leaderBoard",
  //   path: "/leaderboard",
  //   title: "LeaderBoard",
  //   translateKey: "leaderboard",
  //   icon: "leaderboard",
  //   type: NAV_ITEM_TYPE_ITEM,
  //   authority: [],
  //   subMenu: [],
  // },
  // {
  //   key: "tournament",
  //   path: "/tournament",
  //   title: "Company Sales",
  //   translateKey: "tournament",
  //   icon: "payemnt",
  //   type: NAV_ITEM_TYPE_ITEM,
  //   authority: [],
  //   subMenu: [],
  // },

  {
    key: "billing",
    path: "/billing",
    title: "Company Accounts",
    translateKey: "billing",
    icon: "user",
    type: NAV_ITEM_TYPE_ITEM,
    authority: [],
    subMenu: [],
  },
  {
    key: "create-sales-payment",
    path: "/create-sales-payment",
    title: "Receive Payment",
    translateKey: "receivePayment",
    icon: "payemnt",
    type: NAV_ITEM_TYPE_ITEM,
    authority: [],
    subMenu: [],
  },
  {
    key: "ledger-summary",
    path: "/ledger-summary",
    title: "Ledger Summary",
    translateKey: "ledgerSummary",
    icon: "payemnt",
    type: NAV_ITEM_TYPE_ITEM,
    authority: ["admin", "manager"],
    subMenu: [],
  },
  {
    key: "purchase-ledger-summary",
    path: "/purchase-ledger-summary",
    title: "Purchase Ledger",
    translateKey: "purchaseLedgerSummary",
    icon: "payemnt",
    type: NAV_ITEM_TYPE_ITEM,
    authority: ["admin", "manager"],
    subMenu: [],
  },
  {
    key: "extrudingAccount",
    path: "/extrudingAccount",
    title: "Extruding Account",
    translateKey: "tournament",
    icon: "payemnt",
    type: NAV_ITEM_TYPE_ITEM,
    authority: [],
    subMenu: [],
  },
  // {
  //   key: "tournament",
  //   path: "/tournament",
  //   title: "For Specific User",
  //   translateKey: "tournament",
  //   icon: "payemnt",
  //   type: NAV_ITEM_TYPE_ITEM,
  //   authority: [],
  //   subMenu: [],
  // },
  // {
  //   key: "payment",
  //   path: "/payment",
  //   title: "Transaction",
  //   translateKey: "payment",
  //   icon: "payemnt",
  //   type: NAV_ITEM_TYPE_ITEM,
  //   authority: [],
  //   subMenu: [],
  // },
  //   {
  //     key: "tournament",
  //     path: "/tournament",
  //     title: "Tournament Management",
  //     translateKey: "report",
  //     icon: "report",
  //     type: NAV_ITEM_TYPE_ITEM,
  //     authority: [],
  //     subMenu: [],
  //   },
  // {
  //   key: "PushNotification",
  //   path: "/PushNotification",
  //   title: "News/Alerts",
  //   translateKey: "News/Alerts",
  //   icon: "notification",
  //   type: NAV_ITEM_TYPE_ITEM,
  //   authority: [],
  //   subMenu: [],
  // },
  // {
  //   key: "spinMachine",
  //   path: "/SpinMachineConfiguration",
  //   title: "SpinMachineConfiguration",
  //   translateKey: "SpinMachineConfiguration",
  //   icon: "settings",
  //   type: NAV_ITEM_TYPE_ITEM,
  //   authority: [],
  //   subMenu: [],
  // },
];

export default navigationConfig;
